### ISSUE TITLE
No motor.h in library

### ISSUE THREAD

**Issue by djmerrill** [NVSL/gadgetron-software-libraries#1]

**Comment by djmerrill** [comment]
Again, there is no Motor.h in the library when you install from online. This is critical for the ERSP students.

**Comment by jgarzagu** [comment]
I haven't created a new release for the Arduino Library Manager.
Is the Library working good or is there any change you or Michael added?

**Comment by stevenjswanson** [comment]
Jorge, please fix asap

-steve

## 

Composed on (and maybe dictated to) my phone.

On Oct 26, 2016, at 12:10, djmerrill notifications@github.com wrote:

Again, there is no Motor.h in the library when you install from online.
This is critical for the ERSP students.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/NVSL/gadgetron-software-libraries/issues/1#issuecomment-256447678,
or mute the thread

**Comment by djmerrill** [comment]
I did add some fixes yesterday. Seems to be working when I install manually, but not from the manager.

Best regards,
Devon

**Comment by jgarzagu** [comment]
The updated library with Motor.h is now on the Arduino Library Manager.

Best, 
Jorge
